// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var BalanceRequest = BalanceRequest.FromJson(jsonString);

using Newtonsoft.Json;

namespace WorkshopThirdPart
{
    public partial class BalanceRequest
    {
        [JsonProperty("userpass")] public string Userpass { get; set; }

        [JsonProperty("method")] public string Method { get; set; }

        [JsonProperty("coin")] public string Coin { get; set; }
    }

    public partial class BalanceRequest
    {
        public static BalanceRequest FromJson(string json) =>
            JsonConvert.DeserializeObject<BalanceRequest>(json, Converter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this BalanceRequest self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }
}